# GitLab CI configuration file for building SCHISM-ESMF docker
# images based on ubuntu
# 
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum hereon
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor Carsten Lemmen <carsten.lemmen@hereon.de

# First stage checks for metadata (licenses)
stages:
    - lint
    - build-schism
    - build-schism-esmf
    - docker
    - test

variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    VERSION: v8.4.0
    CONTAINER_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/schism-esmf:${VERSION}-${COMMUNICATOR}
    #CONTAINER_REGISTRY_BASEIMAGE: registry.hzdr.de/mossco/esmf-docker/esmf:${VERSION}-${COMMUNICATOR}
    CONTAINER_REGISTRY_BASEIMAGE: platipodium/esmf:${VERSION}-${COMMUNICATOR}
    SCHISM_DIR: "/builds/schism/schism/devel/schism"
    SCHISM_BUILD_DIR: "/builds/schism/schism/devel/schism/build"
    SCHISM_ESMF_DIR: "/builds/schism/schism-esmf/devel/schism-esmf"
    OLDIO: "ON"
    TVD_LIM: "SB"
 
license-compliance:
    image: python:3.11
    stage: lint
    before_script:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install
    script:
        - poetry run reuse lint
    allow_failure: true

build-schism: 
    image: ${CONTAINER_REGISTRY_BASEIMAGE}
    stage: build-schism

    parallel:
        matrix:
            - COMMUNICATOR: ["openmpi", "mpich"]

    before_script:
        - git clone  --branch master --depth 1 https://github.com/schism-dev/schism ${SCHISM_DIR}
    script: 
        - mkdir -p ${SCHISM_BUILD_DIR}
        - cmake -S ${SCHISM_DIR}/src -B ${SCHISM_BUILD_DIR} -DOLDIO=${OLDIO} -DTVD_LIM=${TVD_LIM}
        - make -C ${SCHISM_BUILD_DIR} -j8 pschism
        - ls -1 ./devel/schism/build/lib/
    artifacts:
        paths: 
            - ./devel/schism/build/lib/
    allow_failure: true
    interruptible: true

build-schism-esmf: 
    image: ${CONTAINER_REGISTRY_BASEIMAGE}
    stage: build-schism-esmf
    dependencies: 
      - build-schism
    parallel:
        matrix:
            - COMMUNICATOR: ["openmpi", "mpich"]
    before_script:
        - git clone --branch master --depth 1 https://github.com/schism-dev/schism-esmf ${SCHISM_ESMF_DIR}
    script: 
        - make -C ${SCHISM_ESMF_DIR} -j8 all
    allow_failure: true
    interruptible: true

build-docker:
    image: docker:20.10.22
    services:
        - docker:20.10.22-dind
    parallel:
        matrix:
            - COMMUNICATOR: ["openmpi", "mpich"]
    allow_failure: true
    interruptible: true
    stage: docker
    before_script: 
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

    script:
        - docker build -t ${CONTAINER_REGISTRY_IMAGE} --build-arg VERSION=${VERSION} --build-arg COMMUNICATOR=${COMMUNICATOR} .
        - docker push ${CONTAINER_REGISTRY_IMAGE}

test-docker:
    image: docker:20.10.22
    services:
        - docker:20.10.22-dind
    parallel:
        matrix:
            - COMMUNICATOR: ["openmpi", "mpich"]
    allow_failure: true
    interruptible: true
    stage: test
    before_script: 
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

    script:
        - docker pull ${CONTAINER_REGISTRY_IMAGE}
        - docker run ${CONTAINER_REGISTRY_IMAGE} /usr/local/bin/ESMF_PrintInfo
